version: '2'

services:
  ratings-db:
    image: postgres
    ports:
     - "5432:5432"
  ratings-ms:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - ratings-db
