version: '2'

services:
  ratings-db:
    image: postgres
    ports:
     - "7003:5432"
  ratings-ms:
    build: .
    command: python3 manage.py runserver 0.0.0.0:6003
    ports:
      - "6003:6003"
    depends_on:
      - ratings-db
