# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('car_rating', models.IntegerField(choices=[(1, b'Poor'), (2, b'Bad'), (3, b'Okay'), (4, b'Good'), (5, b'Great')], default=-1)),
                ('driver_rating', models.IntegerField(choices=[(1, b'Poor'), (2, b'Bad'), (3, b'Okay'), (4, b'Good'), (5, b'Great')], default=-1)),
                ('average_rating', models.FloatField(default=0)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
